# Generated by Django 6.0.4 on 2026-04-23 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
