# Generated by Django 5.2.8 on 2026-05-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', "O'qituvchi"), ('student', 'Talaba'), ('parent', 'Ota-ona')], default='admin', max_length=10),
        ),
    ]
