# Generated by Django 5.2.8 on 2026-05-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_uuid_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_password',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Parol (ochiq)'),
        ),
    ]
