# Generated by Django 6.0.4 on 2026-05-19 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_login_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_password',
        ),
    ]
