# Generated by Django 6.0.4 on 2026-04-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('capacity', models.PositiveIntegerField()),
                ('room_type', models.CharField(choices=[('lecture', "Ma'ruza"), ('lab', 'Laboratoriya'), ('practice', 'Amaliyot')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('credits', models.PositiveIntegerField()),
            ],
        ),
    ]
