# Generated by Django 6.0.4 on 2026-04-23 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_group_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='room',
        ),
        migrations.AddField(
            model_name='timetable',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.classroom'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.group'),
        ),
    ]
