# Generated by Django 6.0.4 on 2026-05-05 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_group_subjects_group_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='timetable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.timetable'),
        ),
        migrations.CreateModel(
            name='LessonJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('topic', models.CharField(max_length=255, verbose_name='Dars mavzusi')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.timetable')),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='lesson',
        ),
        migrations.CreateModel(
            name='JournalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True, verbose_name='Qatnashdi')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Baho')),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academy.lessonjournal')),
            ],
            options={
                'unique_together': {('lesson', 'student')},
            },
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
