# Generated by Django 6.0.4 on 2026-05-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_exam_notification_payment_studymaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Kurs'),
        ),
    ]
