# Generated by Django 6.0.4 on 2026-05-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_student_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Sana')),
                ('description', models.CharField(max_length=255, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Bayram kuni',
                'verbose_name_plural': 'Bayram kunlari',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Semestr nomi')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('is_active', models.BooleanField(default=False, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Semestr',
                'verbose_name_plural': 'Semestrlar',
            },
        ),
    ]
