# Generated by Django 5.2.8 on 2026-05-11 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0016_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name="O'quv yili")),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('is_active', models.BooleanField(default=False, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "O'quv yili",
                'verbose_name_plural': "O'quv yillari",
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Fakultet nomi')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Fakultet kodi')),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': 'Fakultetlar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='semester',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.academicyear', verbose_name="O'quv yili"),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', "Qo'shish"), ('update', 'Tahrirlash'), ('delete', "O'chirish")], max_length=10, verbose_name='Amal')),
                ('model_name', models.CharField(max_length=50, verbose_name='Model')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Objekt ID')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Objekt nomi')),
                ('details', models.TextField(blank=True, verbose_name='Tafsilot')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit loglar',
                'ordering': ['-created_at'],
            },
        ),
    ]
