# Generated by Django 6.0.4 on 2026-05-19 22:39

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0020_add_uuid_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalgrade',
            name='is_present',
        ),
        migrations.AddField(
            model_name='journalgrade',
            name='status',
            field=models.CharField(choices=[('present', 'Bor'), ('absent', "Yo'q"), ('late', 'Kechikdi')], default='present', max_length=10, verbose_name='Davomat'),
        ),
        migrations.AlterField(
            model_name='lessonjournal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subject',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
